# Generated by Django 3.2.9 on 2022-07-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
