# Generated by Django 3.2.9 on 2022-07-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0004_auto_20220704_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Нaзвание')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='фото')),
                ('full_text', models.TextField(verbose_name='Cтатья')),
                ('date', models.DateTimeField(verbose_name='Дaта публикации')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
