# Generated by Django 3.2.9 on 2022-07-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220612_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BanerImage',
        ),
    ]
