# Generated by Django 3.2.9 on 2022-06-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
